# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('temp', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('duration', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('img', models.ImageField(blank=True, max_length=3000, upload_to='')),
                ('autom', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('directions', models.ManyToManyField(to='cookbook.Direction')),
            ],
        ),
    ]
